# Matrix Algebra
### Importation

In [1]:
import numpy as np
import tensorflow as tf
import matplotlib as mlt
from numpy import linalg as alg

### Functions

In [2]:
M       = np.array
t       = np.transpose
I       = np.identity
reshape = np.reshape
o       = np.multiply
x       = np.dot
pow     = alg.matrix_power
inv     = alg.inv
det     = alg.det

rows    = lambda M : np.size(M, 0)
cols    = lambda M : np.size(M, 1)

In [3]:
def matrixRound(M, n):
    r = rows(M)
    c = cols(M)
    M = M.flatten()
    for i in range(0, len(M)):
        M[i] = round(M[i],n)
    M = reshape(M,(r,c))
    return M


In [4]:
def randomM(d1,d2,_round = 0, factor = 10):
    M = np.random.rand(d1,d2)
    M = M * factor
    M = matrixRound(M,_round)
    return M

In [5]:
def gauss(M):
    Mprime = M.copy()
    c = cols(M)-1
    for i in range(0, c):
        for j in range(0, c-i):
            Mprime[c-j,:] = Mprime[c-j-1,i]*Mprime[c-j,:] - Mprime[c-j,i]*Mprime[c-j-1,:] 
    return Mprime

In [6]:
def r(M):
    A = M.copy()
    A = gauss(A)
    if(cols(A)>rows(A)):
        ran = rows(A)
    else:
        ran = cols(A)
    c = ran
    
    for i in range(0, c):
        n = 0
        
        for j in range(0, c):
            if(A[i,j] == 0):
                n = n+1
                
            if(n == c):
                ran = ran -1
            
    return ran 
            

In [7]:
def Cramer(M,b, log = True):
    X = np.zeros(cols(M))
    detM = det(M)
    unknow = ['x','y','z','t']
    
    for i in range(0, len(X)):
        Mx = M.copy()
        Mx[:,i] = t(b)
        detMx = det(Mx)
        X[i] = detMx/detM
        
        if(log):
            if(len(X) <= len(unknow)):
                print(unknow[i], ' = ', X[i])
            else:
                print('x[',i,'] = ', X[i])
    return X

In [8]:
def solve(M, b = 0, cramer = True, log = True):
    E = 'E: wrong dimensions: vector B must have number of terms equal to rows number of A.'
    if(type(b) == int):
        b = np.zeros((rows(M)))   
    if(cramer):
        if(len(b) == rows(M)):
            print('solved')
            return Cramer(M, b, log)
        elif(len(t(b)) == rows(M)):
            print('solved with transposed b')
            return Cramer(M, t(b), log)
        else:
            print(E)
            
    else:
        if(len(b) == rows(M)):
            print('solved with numpy')
            return alg.solve(M, b)
        elif(len(t(b)) == rows(M)):
            print('solved with numpy and transposed b')
            return alg.solve(M, t(b))
        else:
            print(E)
    

### Operations

In [9]:
d = 4
C = randomM(d,d)
B = randomM(d,1)
sol = solve(C, B)

solved
x  =  1.7288842544316996
y  =  -0.2669447340980186
z  =  -1.0375391032325336
t  =  0.6235662148070908


In [10]:
d= 3
C = randomM(d,d, factor = 3) 

print(C)
print(gauss(C))
print(r(C))

[[2. 2. 1.]
 [0. 3. 1.]
 [0. 1. 1.]]
[[2. 2. 1.]
 [0. 6. 2.]
 [0. 0. 0.]]
2
